#!/bin/bash


echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ";
echo "                                                                                                           dddddddd                                                                                                                                                                                                                                                                                                                                                                              ";
echo "        CCCCCCCCCCCCC                                  lllllll      kkkkkkkk             iiii              d::::::d                      lllllll                                      kkkkkkkk                         tttt         hhhhhhh                                  iiii                                                                                                                                    tttt                                                                    !!! ";
echo "     CCC::::::::::::C                                  l:::::l      k::::::k            i::::i             d::::::d                      l:::::l                                      k::::::k                      ttt:::t         h:::::h                                 i::::i                                                                                                                                ttt:::t                                                                   !!:!!";
echo "   CC:::::::::::::::C                                  l:::::l      k::::::k             iiii              d::::::d                      l:::::l                                      k::::::k                      t:::::t         h:::::h                                  iiii                                                                                                                                 t:::::t                                                                   !:::!";
echo "  C:::::CCCCCCCC::::C                                  l:::::l      k::::::k                               d:::::d                       l:::::l                                      k::::::k                      t:::::t         h:::::h                                                                                                                                                                       t:::::t                                                                   !:::!";
echo " C:::::C       CCCCCC   ooooooooooo      ooooooooooo    l::::l       k:::::k    kkkkkkkiiiiiii     ddddddddd:::::d     ssssssssss         l::::l    ooooooooooo       cccccccccccccccc k:::::k    kkkkkkk     ttttttt:::::ttttttt    h::::h hhhhh           eeeeeeeeeeee   iiiiiiirrrrr   rrrrrrrrr            cccccccccccccccc   ooooooooooo      mmmmmmm    mmmmmmm   ppppp   ppppppppp   uuuuuu    uuuuuuttttttt:::::ttttttt        eeeeeeeeeeee    rrrrr   rrrrrrrrr       ssssssssss   !:::!";
echo "C:::::C               oo:::::::::::oo  oo:::::::::::oo  l::::l       k:::::k   k:::::k i:::::i   dd::::::::::::::d   ss::::::::::s        l::::l  oo:::::::::::oo   cc:::::::::::::::c k:::::k   k:::::k      t:::::::::::::::::t    h::::hh:::::hhh      ee::::::::::::ee i:::::ir::::rrr:::::::::r         cc:::::::::::::::c oo:::::::::::oo  mm:::::::m  m:::::::mm p::::ppp:::::::::p  u::::u    u::::ut:::::::::::::::::t      ee::::::::::::ee  r::::rrr:::::::::r    ss::::::::::s  !:::!";
echo "C:::::C              o:::::::::::::::oo:::::::::::::::o l::::l       k:::::k  k:::::k   i::::i  d::::::::::::::::d ss:::::::::::::s       l::::l o:::::::::::::::o c:::::::::::::::::c k:::::k  k:::::k       t:::::::::::::::::t    h::::::::::::::hh   e::::::eeeee:::::eei::::ir:::::::::::::::::r       c:::::::::::::::::co:::::::::::::::om::::::::::mm::::::::::mp:::::::::::::::::p u::::u    u::::ut:::::::::::::::::t     e::::::eeeee:::::eer:::::::::::::::::r ss:::::::::::::s !:::!";
echo "C:::::C              o:::::ooooo:::::oo:::::ooooo:::::o l::::l       k:::::k k:::::k    i::::i d:::::::ddddd:::::d s::::::ssss:::::s      l::::l o:::::ooooo:::::oc:::::::cccccc:::::c k:::::k k:::::k        tttttt:::::::tttttt    h:::::::hhh::::::h e::::::e     e:::::ei::::irr::::::rrrrr::::::r     c:::::::cccccc:::::co:::::ooooo:::::om::::::::::::::::::::::mpp::::::ppppp::::::pu::::u    u::::utttttt:::::::tttttt    e::::::e     e:::::err::::::rrrrr::::::rs::::::ssss:::::s!:::!";
echo "C:::::C              o::::o     o::::oo::::o     o::::o l::::l       k::::::k:::::k     i::::i d::::::d    d:::::d  s:::::s  ssssss       l::::l o::::o     o::::oc::::::c     ccccccc k::::::k:::::k               t:::::t          h::::::h   h::::::he:::::::eeeee::::::ei::::i r:::::r     r:::::r     c::::::c     ccccccco::::o     o::::om:::::mmm::::::mmm:::::m p:::::p     p:::::pu::::u    u::::u      t:::::t          e:::::::eeeee::::::e r:::::r     r:::::r s:::::s  ssssss !:::!";
echo "C:::::C              o::::o     o::::oo::::o     o::::o l::::l       k:::::::::::k      i::::i d:::::d     d:::::d    s::::::s            l::::l o::::o     o::::oc:::::c              k:::::::::::k                t:::::t          h:::::h     h:::::he:::::::::::::::::e i::::i r:::::r     rrrrrrr     c:::::c             o::::o     o::::om::::m   m::::m   m::::m p:::::p     p:::::pu::::u    u::::u      t:::::t          e:::::::::::::::::e  r:::::r     rrrrrrr   s::::::s      !:::!";
echo "C:::::C              o::::o     o::::oo::::o     o::::o l::::l       k:::::::::::k      i::::i d:::::d     d:::::d       s::::::s         l::::l o::::o     o::::oc:::::c              k:::::::::::k                t:::::t          h:::::h     h:::::he::::::eeeeeeeeeee  i::::i r:::::r                 c:::::c             o::::o     o::::om::::m   m::::m   m::::m p:::::p     p:::::pu::::u    u::::u      t:::::t          e::::::eeeeeeeeeee   r:::::r                  s::::::s   !!:!!";
echo " C:::::C       CCCCCCo::::o     o::::oo::::o     o::::o l::::l       k::::::k:::::k     i::::i d:::::d     d:::::d ssssss   s:::::s       l::::l o::::o     o::::oc::::::c     ccccccc k::::::k:::::k               t:::::t    tttttth:::::h     h:::::he:::::::e           i::::i r:::::r                 c::::::c     ccccccco::::o     o::::om::::m   m::::m   m::::m p:::::p    p::::::pu:::::uuuu:::::u      t:::::t    tttttte:::::::e            r:::::r            ssssss   s:::::s  !!! ";
echo "  C:::::CCCCCCCC::::Co:::::ooooo:::::oo:::::ooooo:::::ol::::::l     k::::::k k:::::k   i::::::id::::::ddddd::::::dds:::::ssss::::::s     l::::::lo:::::ooooo:::::oc:::::::cccccc:::::ck::::::k k:::::k              t::::::tttt:::::th:::::h     h:::::he::::::::e         i::::::ir:::::r                 c:::::::cccccc:::::co:::::ooooo:::::om::::m   m::::m   m::::m p:::::ppppp:::::::pu:::::::::::::::uu    t::::::tttt:::::te::::::::e           r:::::r            s:::::ssss::::::s     ";
echo "   CC:::::::::::::::Co:::::::::::::::oo:::::::::::::::ol::::::l     k::::::k  k:::::k  i::::::i d:::::::::::::::::ds::::::::::::::s      l::::::lo:::::::::::::::o c:::::::::::::::::ck::::::k  k:::::k             tt::::::::::::::th:::::h     h:::::h e::::::::eeeeeeee i::::::ir:::::r                  c:::::::::::::::::co:::::::::::::::om::::m   m::::m   m::::m p::::::::::::::::p  u:::::::::::::::u    tt::::::::::::::t e::::::::eeeeeeee   r:::::r            s::::::::::::::s  !!! ";
echo "     CCC::::::::::::C oo:::::::::::oo  oo:::::::::::oo l::::::l     k::::::k   k:::::k i::::::i  d:::::::::ddd::::d s:::::::::::ss       l::::::l oo:::::::::::oo   cc:::::::::::::::ck::::::k   k:::::k              tt:::::::::::tth:::::h     h:::::h  ee:::::::::::::e i::::::ir:::::r                   cc:::::::::::::::c oo:::::::::::oo m::::m   m::::m   m::::m p::::::::::::::pp    uu::::::::uu:::u      tt:::::::::::tt  ee:::::::::::::e   r:::::r             s:::::::::::ss  !!:!!";
echo "        CCCCCCCCCCCCC   ooooooooooo      ooooooooooo   llllllll     kkkkkkkk    kkkkkkkiiiiiiii   ddddddddd   ddddd  sssssssssss         llllllll   ooooooooooo       cccccccccccccccckkkkkkkk    kkkkkkk               ttttttttttt  hhhhhhh     hhhhhhh    eeeeeeeeeeeeee iiiiiiiirrrrrrr                     cccccccccccccccc   ooooooooooo   mmmmmm   mmmmmm   mmmmmm p::::::pppppppp        uuuuuuuu  uuuu        ttttttttttt      eeeeeeeeeeeeee   rrrrrrr              sssssssssss     !!! ";
echo "                                                                                                                                                                                                                                                                                                                                                                         p:::::p                                                                                                                 ";
echo "                                                                                                                                                                                                                                                                                                                                                                         p:::::p                                                                                                                 ";
echo "                                                                                                                                                                                                                                                                                                                                                                        p:::::::p                                                                                                                ";
echo "                                                                                                                                                                                                                                                                                                                                                                        p:::::::p                                                                                                                ";
echo "                                                                                                                                                                                                                                                                                                                                                                        p:::::::p                                                                                                                ";
echo "                                                                                                                                                                                                                                                                                                                                                                        ppppppppp                                                                                                                ";
echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ";
